# Generated by Django 4.2.23 on 2025-07-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post_status",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
