# Generated by Django 4.2.23 on 2025-07-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_alter_post_status_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post_status",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
