# Generated by Django 4.2.26 on 2025-12-03 15:19

from django.db import migrations

def create_type_messages(apps, schema_editor):
    TypeMessage = apps.get_model('marketplace', 'TypeMessage')

    types = [
        {"type": "texte"},
        {"type": "image"},
        {"type": "system"},
    ]

    for t in types:
        TypeMessage.objects.get_or_create(type=t["type"])

class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0007_auto_20251203_1818"),
    ]

    operations = [
        migrations.RunPython(create_type_messages),
    ]
