# Generated by Django 4.2.27 on 2026-01-29 17:34

from django.db import migrations

def create_labels(apps, schema_editor):
    Label = apps.get_model('marketplace', 'Label')
    labels = [
        {"name": "Bio", "color": "#10b481"},         # vert principal
        {"name": "Promo", "color": "#17a2b8"},       # bleu doux
        {"name": "Nouveau", "color": "#6f42c1"},     # violet doux
        {"name": "Populaire", "color": "#ffc107"},   # jaune chaud
        {"name": "Fermier", "color": "#8B4513"},     # marron naturel
        {"name": "Éco", "color": "#20c997"},         # vert clair
        {"name": "Local", "color": "#fd7e14"},       # orange doux
        {"name": "Vente flash", "color": "#6610f2"}, # violet vif
    ]
    for l in labels:
        Label.objects.get_or_create(
            name=l["name"],        # ⚡ corrigé
            defaults={"color": l["color"]}
        )

class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0015_message_is_read"),
    ]

    operations = [
        migrations.RunPython(create_labels),
    ]
