# Generated by Django 4.2.27 on 2026-02-09 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0016_auto_20260129_2034"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("MVOLA", "MVola"),
                            ("ORANGE_MONEY", "Orange Money"),
                            ("AIRTEL_MONEY", "Airtel Money"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_number",
                    models.CharField(
                        help_text="Numéro utilisé pour le paiement", max_length=30
                    ),
                ),
                (
                    "transaction_reference",
                    models.CharField(max_length=100, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("SUCCESS", "Succès"),
                            ("FAILED", "Échoué"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bid",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="marketplace.bid",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="marketplace.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "ordering": ["-created_at"],
            },
        ),
    ]
