# Generated by Django 4.2.23 on 2026-02-16 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0017_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "platform_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("payment_method", models.CharField(default="card", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting_payment", "Awaiting Payment"),
                            ("funds_secured", "Funds Secured"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="awaiting_payment",
                        max_length=30,
                    ),
                ),
                ("buyer_confirmation", models.BooleanField(default=False)),
                ("seller_confirmation", models.BooleanField(default=False)),
                (
                    "refunded_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("failure_reason", models.TextField(blank=True, null=True)),
                ("dispute_id", models.CharField(blank=True, max_length=255, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="marketplace.bid",
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments_as_buyer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="marketplace.currency",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments_as_seller",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "ordering": ["-transaction_date"],
            },
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
