# Generated by Django 4.2.23 on 2026-02-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0018_payments_delete_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_account_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
