INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (1, 'Can add log entry', 1, 'add_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (2, 'Can change log entry', 1, 'change_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (3, 'Can delete log entry', 1, 'delete_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (4, 'Can view log entry', 1, 'view_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (5, 'Can add permission', 2, 'add_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (6, 'Can change permission', 2, 'change_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (7, 'Can delete permission', 2, 'delete_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (8, 'Can view permission', 2, 'view_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (9, 'Can add group', 3, 'add_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (10, 'Can change group', 3, 'change_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (11, 'Can delete group', 3, 'delete_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (12, 'Can view group', 3, 'view_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (13, 'Can add content type', 4, 'add_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (14, 'Can change content type', 4, 'change_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (15, 'Can delete content type', 4, 'delete_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (16, 'Can view content type', 4, 'view_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (17, 'Can add session', 5, 'add_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (18, 'Can change session', 5, 'change_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (19, 'Can delete session', 5, 'delete_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (20, 'Can view session', 5, 'view_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (21, 'Can add user', 6, 'add_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (22, 'Can change user', 6, 'change_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (23, 'Can delete user', 6, 'delete_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (24, 'Can view user', 6, 'view_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (25, 'Can add categorie post', 7, 'add_categoriepost');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (26, 'Can change categorie post', 7, 'change_categoriepost');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (27, 'Can delete categorie post', 7, 'delete_categoriepost');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (28, 'Can view categorie post', 7, 'view_categoriepost');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (29, 'Can add categorie user', 8, 'add_categorieuser');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (30, 'Can change categorie user', 8, 'change_categorieuser');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (31, 'Can delete categorie user', 8, 'delete_categorieuser');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (32, 'Can view categorie user', 8, 'view_categorieuser');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (33, 'Can add chat', 9, 'add_chat');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (34, 'Can change chat', 9, 'change_chat');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (35, 'Can delete chat', 9, 'delete_chat');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (36, 'Can view chat', 9, 'view_chat');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (37, 'Can add currency', 10, 'add_currency');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (38, 'Can change currency', 10, 'change_currency');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (39, 'Can delete currency', 10, 'delete_currency');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (40, 'Can view currency', 10, 'view_currency');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (41, 'Can add label', 11, 'add_label');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (42, 'Can change label', 11, 'change_label');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (43, 'Can delete label', 11, 'delete_label');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (44, 'Can view label', 11, 'view_label');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (45, 'Can add message', 12, 'add_message');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (46, 'Can change message', 12, 'change_message');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (47, 'Can delete message', 12, 'delete_message');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (48, 'Can view message', 12, 'view_message');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (49, 'Can add message_status', 13, 'add_message_status');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (50, 'Can change message_status', 13, 'change_message_status');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (51, 'Can delete message_status', 13, 'delete_message_status');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (52, 'Can view message_status', 13, 'view_message_status');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (53, 'Can add post', 14, 'add_post');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (54, 'Can change post', 14, 'change_post');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (55, 'Can delete post', 14, 'delete_post');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (56, 'Can view post', 14, 'view_post');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (57, 'Can add post_status', 15, 'add_post_status');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (58, 'Can change post_status', 15, 'change_post_status');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (59, 'Can delete post_status', 15, 'delete_post_status');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (60, 'Can view post_status', 15, 'view_post_status');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (61, 'Can add tag', 16, 'add_tag');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (62, 'Can change tag', 16, 'change_tag');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (63, 'Can delete tag', 16, 'delete_tag');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (64, 'Can view tag', 16, 'view_tag');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (65, 'Can add type message', 17, 'add_typemessage');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (66, 'Can change type message', 17, 'change_typemessage');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (67, 'Can delete type message', 17, 'delete_typemessage');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (68, 'Can view type message', 17, 'view_typemessage');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (69, 'Can add type pdf', 18, 'add_typepdf');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (70, 'Can change type pdf', 18, 'change_typepdf');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (71, 'Can delete type pdf', 18, 'delete_typepdf');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (72, 'Can view type pdf', 18, 'view_typepdf');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (73, 'Can add type post', 19, 'add_typepost');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (74, 'Can change type post', 19, 'change_typepost');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (75, 'Can delete type post', 19, 'delete_typepost');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (76, 'Can view type post', 19, 'view_typepost');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (77, 'Can add unit', 20, 'add_unit');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (78, 'Can change unit', 20, 'change_unit');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (79, 'Can delete unit', 20, 'delete_unit');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (80, 'Can view unit', 20, 'view_unit');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (81, 'Can add review', 21, 'add_review');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (82, 'Can change review', 21, 'change_review');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (83, 'Can delete review', 21, 'delete_review');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (84, 'Can view review', 21, 'view_review');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (85, 'Can add report', 22, 'add_report');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (86, 'Can change report', 22, 'change_report');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (87, 'Can delete report', 22, 'delete_report');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (88, 'Can view report', 22, 'view_report');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (89, 'Can add product', 23, 'add_product');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (90, 'Can change product', 23, 'change_product');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (91, 'Can delete product', 23, 'delete_product');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (92, 'Can view product', 23, 'view_product');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (93, 'Can add pdf', 24, 'add_pdf');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (94, 'Can change pdf', 24, 'change_pdf');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (95, 'Can delete pdf', 24, 'delete_pdf');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (96, 'Can view pdf', 24, 'view_pdf');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (97, 'Can add notification', 25, 'add_notification');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (98, 'Can change notification', 25, 'change_notification');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (99, 'Can delete notification', 25, 'delete_notification');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (100, 'Can view notification', 25, 'view_notification');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (101, 'Can add post tag', 26, 'add_posttag');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (102, 'Can change post tag', 26, 'change_posttag');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (103, 'Can delete post tag', 26, 'delete_posttag');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (104, 'Can view post tag', 26, 'view_posttag');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (105, 'Can add favorite', 27, 'add_favorite');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (106, 'Can change favorite', 27, 'change_favorite');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (107, 'Can delete favorite', 27, 'delete_favorite');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (108, 'Can view favorite', 27, 'view_favorite');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (109, 'Can add post status relation', 28, 'add_poststatusrelation');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (110, 'Can change post status relation', 28, 'change_poststatusrelation');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (111, 'Can delete post status relation', 28, 'delete_poststatusrelation');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (112, 'Can view post status relation', 28, 'view_poststatusrelation');
